### ISSUE TITLE
Ref-Bonus is not awarded

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyReferral#2]
The Ref-Bonus is not awarded because this request fails (Trace: api-7f4cccb74-dqmcn.608440387839c3d9)
![Image](https://user-images.githubusercontent.com/58751503/192799696-79986f44-bd9f-4b1a-9404-8f2fbc866f81.png)

Discord:
https://discord.com/channels/267680588666896385/1024528186551316590

**Comment by Ekwav** [comment]
No, that request fails because the ref bonus has already been awarded 
> Error calling ReferralUserIdPost: {"Message":"You have already used a referral link"}

Adding handling to forward that message in the Api

**Comment by matthias-luger** [comment]
He doesnt seem to have gotten it though
`{
  "id": 42341,
  "externalId": "40770",
  "balance": 0,
  "availableBalance": 0,
  "owns": [
    {
      "id": 7115,
      "product": {
        "id": 41,
        "title": "Premium",
        "slug": "premium",
        "description": "Premium plan granting various perks",
        "cost": 1800,
        "ownershipSeconds": 2592000,
        "type": "SERVICE"
      },
      "expires": "2022-10-28T04:46:06.276759"
    },
    {
      "id": 7116,
      "product": {
        "id": 44,
        "title": "Basic plan",
        "slug": "starter_premium",
        "description": "Access to basic perks",
        "cost": 1800,
        "ownershipSeconds": 15552000,
        "type": "SERVICE"
      },
      "expires": "2022-10-28T04:46:06.305389"
    }
  ]
}`

**Comment by Ekwav** [comment]
fixed error with https://github.com/Coflnet/SkyApi/commit/17586382b1cb19b3550a6a177e55c3721e201922
